export const DATABASE_SCHOOL = "DATABASE_SCHOOL";
export const SELECTED_SCHOOL = "SELECTED_SCHOOL";
export const CREATE_SCHOOL = "CREATE_SCHOOL";
export const DELETE_SCHOOL = "DELETE_SCHOOL";
export const UPDATE_SCHOOL = "UPDATE_SCHOOL";
