export const DATABASE_COURSE = "DATABASE_COURSE";
export const SELECTED_COURSE = "SELECTED_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
