export const SELECTED_STUDENT = "SELECTED_STUDENT";
export const DATABASE_STUDENT = "DATABASE_STUDENT";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
